### ISSUE TITLE
barcodeScannerDecode() won't necessarily return barcode received after the call

### ISSUE THREAD

**Issue by Bradshawz** [SmartFoodTracker/SmartFoodTrackerDE2#1]
barcodeScannerDecode() needs to flush its buffer upon getting called to guarantee the most recent barcode, can't just straight flush the buffer as there is malloc'd memory. (Also a full queue will currently leak memory in the isr)

**Comment by kohsh** [comment]
Whoops, good point. I'll make sure to check the return value of OSQPost, there is a status to the effect of OS_Q_FULL that is used for this. I agree flushing isn't super easy to do here (do to cleanup of the data and not knowing what is relevant to the current barcode). Your point though is that essentially the barcode scanner should not be allowed to produce barcodes until barcodeScannerDecode() has been called. We can simply Enable/disable the scanner around the core of that routine.

**Comment by kohsh** [comment]
#96e91a963290610479534075b6532e38afaba34a
