### ISSUE TITLE
Using microphone switch while disabled will invert the microphone switch

### ISSUE THREAD

**Issue by Bradshawz** [SmartFoodTracker/SmartFoodTrackerDE2#3]
Going diasble -> up on switch -> down on switch -> enable will cause the next up on switch to finish the read call. Now the switch is permanently in reverse.

**Comment by kohsh** [comment]
This coulllddd be fixed, but doesn't really affect the functionality.

**Comment by Bradshawz** [comment]
Main issue is it is unexpected behavior i can't explain which mean somethings not working as it should. Inversion would make sense and be normal if while disabled i turned it only on and the re-enabled, but currently turning it on then off while disabled will mean once its re enabled it will instantly count as being captured once i flip it to on.

(Example)
Enable -> On -> Off -> Get Capture -> Disable -> On -> Off -> Enable -> On -> Get Capture
 -----------------(Normal)---------------------------------------------------------(Wat)

**Comment by kohsh** [comment]
7aa8752919772be59fe5273e6215dc332ec4c2b3
